#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <string>

using namespace std;

enum MessageType {
	ERROR = 0,

	REGISTER = 1,
    REGISTER_SUCCESS = 2,
    REGISTER_FAILURE = 3,

	LOC_REQUEST = 4,
	LOC_SUCCESS = 5,
	LOC_FAILURE = 6,

	EXECUTE = 7,
	EXECUTE_SUCCESS = 8,
	EXECUTE_FAILURE = 9,

	TERMINATE = 10,

    CACHE_REQUEST = 11
};

enum ReasonCode {
    SUCCESS = 0,
    FUNCTION_OVERRIDDEN = 2,

    FUNCTION_NOT_AVAILABLE = -1,

    SOCKET_UNKNOWN_HOST = -2,
    SOCKET_CONNECTION_FALIURE = -3,
    SOCKET_LOCAL_BIND_FALIURE = -4,
    SOCKET_LOCAL_LISTEN_FALIURE = -5,
    SOCKET_ACCEPT_CLIENT_FAILURE = -6,
    
    INIT_UNSET_BINDER_ADDRESS = -7,
    INIT_BINDER_SOCKET_FAILURE = -8,
    SELECT_FAILED = -9,

    EXECUTION_FAILED = -10
};

#endif